/* MOTOR MADRE — NO EDITAR */
(()=>{"use strict";const $=id=>document.getElementById(id),data=window.QUESTIONNAIRE_DATA||[],intros=window.INTRO_CONTENT||{},op=window.OPINION_CONTENT||{},cfg=window.APP_CONFIG||{},screens=[...document.querySelectorAll('.screen')];
const st={mc:null,intro:null,qi:0,score:0,answers:[],survey:[],si:0,opinion:{},participant:null,started:new Date().toISOString(),finished:null,responseId:null};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function slug(){const q=new URLSearchParams(location.search).get('clase'),f=location.pathname.split('/').pop().replace(/\.html$/i,'').toLowerCase();return data.some(x=>x.slug===q)?q:data.some(x=>x.slug===f)?f:'oppenheimer'}
function show(id,p,label){screens.forEach(x=>x.classList.toggle('active',x.id===id));document.body.classList.toggle('in-intro',id==='screen-intro');$('progress-bar').style.width=`${p}%`;$('step-label').textContent=label||'';scrollTo({top:0,behavior:'smooth'})}
function init(){st.mc=data.find(x=>x.slug===slug());st.intro=intros[st.mc?.slug];if(!st.mc||!st.intro)return document.body.innerHTML='<main class="fatal-error">Falta la configuración de esta masterclass.</main>';document.title=`${st.mc.title} · Fenomenautas`;$('intro-title').textContent=st.intro.portadaTitulo||st.mc.title;$('intro-subtitle').textContent=st.intro.portadaSubtitulo||'';$('intro-copy').textContent=st.intro.portadaTexto;$('eval-intro-title').textContent=st.intro.evaluacionTitulo;$('eval-intro-copy').textContent=st.intro.evaluacionTexto;$('eval-intro-objective').textContent=st.intro.evaluacionObjetivo;show('screen-intro',0,'')}
function shuffled(a){const u=a.find(x=>/no sé/i.test(x.text)),r=a.filter(x=>x!==u);for(let i=r.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[r[i],r[j]]=[r[j],r[i]]}return u?[...r,u]:r}
function startQuiz(){st.qi=0;st.score=0;st.answers=[];renderQuestion();show('screen-quiz',7,'Veamos cuánto aprendiste')}
function renderQuestion(){const q=st.mc.questions[st.qi];$('question-counter').textContent=`Pregunta ${st.qi+1} de ${st.mc.questions.length}`;$('question-text').textContent=q.prompt;$('question-warning').hidden=true;$('question-next').disabled=true;$('options-list').innerHTML='';shuffled(q.options).forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='option-btn';b.innerHTML=`<span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span>`;b.onclick=()=>{[...$('options-list').children].forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('options-list').dataset.key=o.key;$('options-list').dataset.text=o.text;$('question-next').disabled=false};$('options-list').appendChild(b)});$('progress-bar').style.width=`${7+Math.round(st.qi/st.mc.questions.length*33)}%`}
function nextQuestion(){const key=$('options-list').dataset.key;if(!key){$('question-warning').hidden=false;return}const q=st.mc.questions[st.qi],correct=q.scored?key===q.correct:null;if(correct)st.score++;st.answers.push({number:q.number,prompt:q.prompt,selectedOptionKey:key,selectedText:$('options-list').dataset.text,correctOptionKey:q.correct,isCorrect:correct,feedback:q.feedback,scored:q.scored});delete $('options-list').dataset.key;delete $('options-list').dataset.text;if(++st.qi<st.mc.questions.length)return renderQuestion();show('screen-transition',42,'Tu opinión')}
function buildSurvey(){st.survey=[...(op.demographics||[]),...(op.likert||[]).map(x=>({...x,likert:true})),...(op.projection||[]),{...op.comment,textarea:true,optional:true}];st.si=0;renderSurvey();show('screen-survey',45,'Tu opinión')}
function renderSurvey(){const q=st.survey[st.si],box=$('survey-control');$('survey-counter').textContent=`Pregunta ${st.si+1} de ${st.survey.length}`;$('survey-title').textContent=q.title;$('survey-error').hidden=true;if(q.textarea)box.innerHTML=`<textarea id="survey-value" rows="6" placeholder="${esc(q.placeholder||'')}"></textarea>`;else if(q.likert)box.innerHTML=`<div class="likert-scale">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="survey" value="${n}"><span>${n}</span></label>`).join('')}</div><div class="likert-labels"><span>Totalmente en desacuerdo</span><span>Totalmente de acuerdo</span></div>`;else box.innerHTML=`<div class="survey-options">${q.options.map((x,i)=>`<label class="survey-option"><input type="${q.multiple?'checkbox':'radio'}" name="survey" value="${esc(x)}"><span class="option-letter">${String.fromCharCode(65+i)}</span><span>${esc(x)}</span></label>`).join('')}</div>`;$('progress-bar').style.width=`${45+Math.round(st.si/st.survey.length*35)}%`}
function submitSurvey(e){e.preventDefault();const q=st.survey[st.si];let val;if(q.textarea)val=$('survey-value').value.trim();else{const chosen=[...document.querySelectorAll('#survey-control input:checked')].map(x=>x.value);val=q.multiple?chosen:chosen[0]}if(!q.optional&&(!val||(Array.isArray(val)&&!val.length))){$('survey-error').hidden=false;return}st.opinion[q.key]=val||null;if(++st.si<st.survey.length)return renderSurvey();show('screen-data',82,'Tus datos')}
function cleanDni(v){return v.replace(/[.\s-]/g,'')}
async function submitData(e){e.preventDefault();const form=$('data-form'),err=$('form-error');err.hidden=true;if(!form.reportValidity())return;const dni=cleanDni($('participant-dni').value);if(!/^\d{7,8}$/.test(dni)){err.textContent='El DNI debe tener 7 u 8 números.';err.hidden=false;return}st.participant={name:$('participant-name').value.trim(),surname:$('participant-surname').value.trim(),dni,email:$('participant-email').value.trim()};st.finished=new Date().toISOString();$('data-submit').disabled=true;$('data-submit').textContent='Guardando…';showResult();const saved=await save();$('save-status').textContent=saved;$('data-submit').disabled=false}
function payload(){const a=st.answers.filter(x=>x.scored);return {masterclass_slug:st.mc.slug,timestamp_inicio:st.started,timestamp_fin:st.finished,edad:st.opinion.edad,genero:st.opinion.genero,formacion:st.opinion.formacion,disciplina:st.opinion.disciplina,anios_docencia:st.opinion.anios_docencia,nivel_educativo:st.opinion.nivel_educativo,sector:st.opinion.sector,conocia_fenomenautas:st.opinion.conocia_fenomenautas,respuestas_eval:st.answers,puntaje:st.score,aprobado:st.score>=5,nombre:st.participant.name,apellido:st.participant.surname,dni:st.participant.dni,mail:st.participant.email,likert_claridad:+st.opinion.likert_claridad,likert_viabilidad:+st.opinion.likert_viabilidad,likert_innovacion:+st.opinion.likert_innovacion,likert_duracion:+st.opinion.likert_duracion,likert_recomendacion:+st.opinion.likert_recomendacion,proy_usar:st.opinion.proy_usar,proy_valor:st.opinion.proy_valor,proy_desafios:st.opinion.proy_desafios,proy_enfoque:st.opinion.proy_enfoque,comentario:st.opinion.comentario,certificado_generado:false,pais:st.opinion.pais,tiempos_eval:a.map(()=>null),dispositivo:/Mobi|Android/i.test(navigator.userAgent)?'móvil':'escritorio',descargo_pdf:false,descargo_imagen:false}}
async function save(){if(!cfg.supabaseUrl||!cfg.supabaseAnonKey)return'Modo de prueba: las respuestas no se guardaron.';try{const r=await fetch(`${cfg.supabaseUrl.replace(/\/$/,'')}/rest/v1/responses`,{method:'POST',headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(payload())});if(!r.ok){const t=await r.text();if(r.status===409)throw new Error('Ya existe una respuesta para este DNI o correo en esta masterclass.');throw new Error(t)}const rows=await r.json();st.responseId=rows[0]?.id;return'Respuestas guardadas correctamente.'}catch(e){console.error(e);return e.message.startsWith('Ya existe')?e.message:'La actividad terminó, pero no pudo guardarse. Revisá la instalación de Supabase.'}}
function showResult(){const ok=st.score>=5;$('result-score').textContent=st.score;$('result-title').textContent=ok?'¡Aprobaste!':'Gracias por participar';$('result-copy').textContent=ok?'Alcanzaste el puntaje necesario y recibirás un certificado de aprobación.':'No alcanzaste el puntaje de aprobación. Recibirás un certificado de participación.';$('answer-review').innerHTML=st.answers.filter(x=>x.scored).map((x,i)=>`<article class="review-item ${x.isCorrect?'right':'wrong'}"><strong>${x.isCorrect?'✅':'❌'} Pregunta ${i+1}</strong><p>${esc(x.prompt)}</p><small>${esc(x.feedback||'')}</small></article>`).join('');$('save-status').textContent='Guardando respuestas…';show('screen-result',93,'Tus resultados')}
function showCertificate(){const ok=st.score>=5;$('certificate-banner').textContent=ok?'CERTIFICADO DE APROBACIÓN':'CERTIFICADO DE PARTICIPACIÓN';$('certificate-phrase').textContent=ok?'por haber aprobado la evaluación de la masterclass':'por haber participado de la evaluación de la masterclass';$('certificate-name').textContent=`${st.participant.name} ${st.participant.surname}`;$('certificate-course').textContent=st.mc.title;$('certificate-date').textContent=new Date().toLocaleDateString('es-AR',{day:'numeric',month:'long',year:'numeric'});show('screen-certificate',100,'Certificado');mark('certificado_generado');fit()}
function fit(){const c=$('certificate');c.style.transform='';c.parentElement.style.height='';if(innerWidth<840){const s=Math.min(1,(innerWidth-26)/800);c.style.transform=`scale(${s})`;c.parentElement.style.height=`${c.offsetHeight*s+150}px`}}
async function canvas(){const clone=$('certificate').cloneNode(true),sandbox=document.createElement('div');sandbox.style.cssText='position:fixed;left:-10000px;top:0;width:800px;background:#fdf9ef';clone.style.cssText='width:800px;min-height:590px;margin:0;transform:none';sandbox.appendChild(clone);document.body.appendChild(sandbox);try{await document.fonts?.ready;return await html2canvas(clone,{scale:2,backgroundColor:'#fdf9ef',useCORS:true,width:800,height:clone.scrollHeight})}finally{sandbox.remove()}}
async function mark(field){if(!st.responseId||!cfg.supabaseUrl)return;fetch(`${cfg.supabaseUrl.replace(/\/$/,'')}/rest/v1/responses?id=eq.${st.responseId}`,{method:'PATCH',headers:{apikey:cfg.supabaseAnonKey,Authorization:`Bearer ${cfg.supabaseAnonKey}`,'Content-Type':'application/json'},body:JSON.stringify({[field]:true})}).catch(console.error)}
async function png(){const c=await canvas(),a=document.createElement('a');a.download=`certificado-${st.mc.slug}.png`;a.href=c.toDataURL('image/png');a.click();mark('descargo_imagen')}
async function pdf(){const c=await canvas(),{jsPDF}=window.jspdf,p=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),w=p.internal.pageSize.getWidth()-20,h=w*c.height/c.width;p.addImage(c.toDataURL('image/png'),'PNG',10,(p.internal.pageSize.getHeight()-h)/2,w,h);p.save(`certificado-${st.mc.slug}.pdf`);mark('descargo_pdf')}
$('intro-next').onclick=()=>show('screen-eval-intro',4,'Veamos cuánto aprendiste');$('eval-start').onclick=startQuiz;$('question-next').onclick=nextQuestion;$('survey-start').onclick=buildSurvey;$('survey-form').onsubmit=submitSurvey;$('data-form').onsubmit=submitData;$('certificate-show').onclick=showCertificate;$('download-png').onclick=png;$('download-pdf').onclick=pdf;addEventListener('resize',fit);init()})();
